### ISSUE TITLE
I uh... think this is what you're looking for?

### ISSUE THREAD

**Issue by Dasonk** [csurfer/gitlang#1]
Github uses this to detect language: https://github.com/github/linguist

so I think this is the list you want: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by Dasonk** [comment]
This is the help page that led me to that by the way: https://help.github.com/articles/about-repository-languages/

**Comment by csurfer** [comment]
@Dasonk : Thanks for bringing it to my attention. I somehow missed it. I should have checked github help pages before anywhere else.

I am leaving this repo as is, to enable easy readability but have added the above link in the README along with a thank you note to you for pointing it out.
